export const DEPARTMENTS = [
  { name: "All Departments", value: "all" },
  { name: "Cardiology", value: "cardiology" },
  { name: "Emergency", value: "emergency" },
  { name: "Pediatrics", value: "pediatrics" },
  { name: "Radiology", value: "radiology" },
  { name: "Oncology", value: "oncology" },
  { name: "Orthopedics", value: "orthopedics" },
  { name: "Gynecology", value: "gynecology" },
  { name: "Obstetrics", value: "obstetrics" },
  { name: "Neurology", value: "neurology" },
  { name: "Urology", value: "urology" },
  { name: "Gastroenterology", value: "gastroenterology" },
  { name: "Dermatology", value: "dermatology" },
  { name: "Psychiatry", value: "psychiatry" },
  { name: "Surgery", value: "surgery" },
  { name: "Internal Medicine", value: "internal_medicine" },
  { name: "Ophthalmology", value: "ophthalmology" },
  { name: "Anesthesiology", value: "anesthesiology" },
  { name: "Pathology", value: "pathology" },
  { name: "Nephrology", value: "nephrology" },
  { name: "Pulmonology", value: "pulmonology" },
  { name: "Pharmacy", value: "pharmacy" },
  { name: "Nutrition", value: "nutrition" },
  { name: "Dentistry", value: "dentistry" },
  { name: "Physiotherapy", value: "physiotherapy" },
  { name: "ENT", value: "ent" },
  { name: "Administration", value: "admin" },
  { name: "Laboratory", value: "laboratory" },
  { name: "IT Support", value: "it_support" },
  { name: "Maintenance", value: "maintenance" },
  { name: "Cleaning", value: "cleaning" },
  { name: "Medical Records", value: "records" },
  { name: "Billing", value: "billing" },
];

export const location = [
  {
    name: "On Site",
    value: "on-site",
  },
  {
    name: "Remote",
    value: "remote",
  },
];
